{"name": "keyboard", "event": "press", "vk": 13}
{"name": "keyboard", "event": "press", "vk": 174}
{"name": "keyboard", "event": "press", "vk": 174}
{"name": "keyboard", "event": "release", "vk": 174}
{"name": "keyboard", "event": "press", "vk": 174}
{"name": "keyboard", "event": "release", "vk": 174}
{"name": "keyboard", "event": "press", "vk": 39}
{"name": "keyboard", "event": "release", "vk": 39}
{"name": "keyboard", "event": "press", "vk": 39}
{"name": "keyboard", "event": "release", "vk": 39}
{"name": "keyboard", "event": "press", "vk": 68}
{"name": "keyboard", "event": "release", "vk": 68}
{"name": "keyboard", "event": "press", "vk": 39}
{"name": "keyboard", "event": "release", "vk": 39}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 32}
{"name": "keyboard", "event": "release", "vk": 32}
{"name": "keyboard", "event": "press", "vk": 27}
